apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
provisioner: {{ .Values.NFS.provisioner }}
parameters:
  archiveOnDelete: "false"