apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "nfs-client-provisioner-%s" .Values.global.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "4"
  labels:
    app: nfs-client-provisioner
  namespace: {{ printf "ns-%s" .Values.global.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: {{ printf "nfs-client-provisioner-%s" .Values.global.name }}
      containers:
        - name: nfs-client-provisioner
          image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.1
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: {{ printf "%s-%s" .Values.NFS.provisioner .Values.global.name }}
            - name: NFS_SERVER
              value: {{ .Values.NFS.ip }}
            - name: NFS_PATH
              value: {{ .Values.NFS.path }}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ .Values.NFS.ip }}
            path: {{ .Values.NFS.path }}