apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wpress-gateway
  namespace: istio-system
  #  annotations:
  #  "helm.sh/hook": "post-install"
  #  "helm.sh/hook-weight": "1"  
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: sec-tls
    hosts:
    - "*"
