apiVersion: v1
kind: Namespace
metadata:
  name: {{ printf "ns-%s" .Values.global.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
  labels:
    {{- include "ns.labels" . | nindent 4 }}