apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "pv-%s" .Values.mysqlDeployment.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: {{ printf "stgcls-%s" .Values.mysqlDeployment.name }}
  nfs:
    {{- include "nfsmysql.details" . | nindent 4 }}