apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ printf "sc-%s" .Values.global.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
provisioner: {{ printf "%s-%s" .Values.NFS.provisioner .Values.global.name }}
parameters:
  archiveOnDelete: "false"
