apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "sec-%s" .Values.global.name }}
  namespace: {{ printf "ns-%s" .Values.global.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
type: Opaque
data:
  mysql-username: cmVuaml0aA==
  mysql-password: cmVuaml0aA==
  mysql-root-password: cm9vdHJlbmppdGg=