apiVersion: v1
kind: Secret
metadata:
  name: sec-wpress
  namespace: ns-wpress
type: Opaque
data:
  mysql-username: cmVuaml0aA==
  mysql-password: cmVuaml0aA==
  mysql-root-password: cm9vdHJlbmppdGg=